#!/usr/bin/perl

# Object interface
use local::lib;
use Text::CSV;

my @rows;
# Read/parse CSV

binmode(STDOUT, ":utf8");

# binary => 1,
my $csv = Text::CSV->new ({ auto_diag => 1, sep_char => "|", decode_utf8 => 1, escape_char => "\"" });
open my $fh, "<:encoding(utf8)", "linktypes.csv" or die "linktypes.csv: $!";

while (my $row = $csv->getline ($fh)) {
    my $name = $row->[1];
    $name =~ s/_/\\_/;

    print "LinkType Value\n: ".$row->[2]."\n\n";
    print "LinkType Name\n: ".$name."\n\n";
    print "Description\n: ".$row->[3]."\n";
    my $ref = $row->[4];
    if(defined($row->[4])) {
        $ref =~ s/\s*$//;
        my $reflen = length($ref);
        if($reflen > 0) {
            $ref =~ s/_/\\_/g;
            print "\nReference\n: ".$ref."\n";
        }
    }
    print "{: spacing=\"compact\"}\n\n\n\n";
    }
close $fh;


